export const DashboardSectionOneAPI = [
  {
    id: "navapi1",
    name: "Managers",
    number: 2,
    link: "/loggedInAdmin/employee",
  },
  {
    id: "navapi2",
    name: "employees",
    number: 11,
    link: "/loggedInAdmin/employee",
  },
  {
    id: "navapi3",
    name: "marchant",
    number: 57,
    link: "/home",
  },
  {
    id: "navapi4",
    name: "customer",
    number: 57,
    link: "/home",
  },
  {
    id: "navapi5",
    name: "emi collection",
    number: 57,
    link: "/home",
  },
  {
    id: "navapi6",
    name: "recurring collection",
    number: 57,
    link: "/home",
  },
  {
    id: "navapi7",
    name: "Late Fee Loan",
    number: 57,
    link: "/home",
  },
  {
    id: "navapi8",
    name: "Late Fee recurring",
    number: 57,
    link: "/home",
  },
  {
    id: "navapi9",
    name: "marchant",
    number: 57,
    link: "/home",
  },
  {
    id: "navapi10",
    name: "Running Loans",
    number: 57,
    link: "/home",
  },
  {
    id: "navapi11",
    name: "Closed Loans",
    number: 57,
    link: "/home",
  },
  {
    id: "navapi12",
    name: "Running recurring",
    number: 57,
    link: "/home",
  },
  {
    id: "navapi13",
    name: "closed recurring",
    number: 57,
    link: "/home",
  },
  {
    id: "navapi14",
    name: "Pending Loan Request",
    number: 57,
    link: "/home",
  },
  {
    id: "navapi5",
    name: "pending recurring request",
    number: 57,
    link: "/home",
  },
  {
    id: "navapi14",
    name: "Total NPA",
    number: 57,
    link: "/home",
  },
  {
    id: "navapi15",
    name: "customer complaint",
    number: 57,
    link: "/home",
  },
];
